name: Build

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [new-release]

jobs:
  generate:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Extract branch
        shell: bash
        run: echo "KEY=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch
      - uses: actions/checkout@v1
      - name: Run Powershell Script
        run: .\build.ps1
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update plugins repo" -a
      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.extracted_branch.outputs.branch }}
